### PR TITLE
GCI: Implement Google Auth with Firebase

### PR DESCRIPTION
**Pull request by HITGIF**
Add sign in button and structure for Google account.
For the [task](https://codein.withgoogle.com/dashboard/task-instances/6389530603028480/)
SCREENSHOTS
screenshot_1515041057
screenshot_1515041053
screenshot_1515041891
screenshot_1515041583

### CODE REVIEW

**Comment by SachinRammoorthy** [comment]
@HITGIF I don't think you can use `google-services.json` for this task.

**Comment by HITGIF** [comment]
@SachinRammoorthy Hmm, just wondering whether that's a requirement or a suggestion

**Comment by KeenWarrior** [comment]
@HITGIF that is more of a requirement

**Comment by KeenWarrior** [comment]
Sorry misclicked

**Comment by HITGIF** [comment]
@KeenWarrior Changes have been made & squashed

**Pull request closed without merging**
