### PR TITLE
Implementation: Launcher (earlier, splash) Screen

### PR DESCRIPTION
**Pull request by divyanshkul**
I have added the splash screen to the project: 
* Clean hover animations, according to the light theme of the app
* **Added a circular progress bar:** This would help when we implement firebase login, the login details could be processed in the background and the splash screen is being shown in front. 
* The splash screen runs for 3.5 seconds for now (this can later be configured along with the background login process)
* Added "Designed by the Jboss Community" at the bottom. 

PS: Travis was giving errors ```Execution failed for task ':app:lint'.``` Fix: updated build.gradle as suggested [here](https://stackoverflow.com/questions/36860021/gradle-build-execution-failed-for-task-applint/36860149) 

Video Demo: [Splash Screen | Lead Management Android | Jboss Community
](https://www.youtube.com/watch?v=AWw5k_c5pAg)
Screenshot: 

 </img>

### CODE REVIEW

**Comment by neelanshsahai** [comment]
@divyanshkul IMO, ignoring the errors is not a good practice...
please provide a screenshot of the log.

**Comment by divyanshkul** [comment]
@neelanshsahai Yes I know that ignoring errors is not a good practice, this workaround was suggested in the travis log and also in stackoverflow, so thought to add it as a temporary fix. Anyway, 

Raw log data [here](https://api.travis-ci.org/v3/job/324692910/log.txt)
Screenshot:
image

Thanks :)

**Comment by divyanshkul** [comment]
@neelanshsahai any ideas or this temporary workaround seems fine?

**Comment by divyanshkul** [comment]
Resolved conflicts after the latest merge.

**Pull request closed without merging**
